version: '3.3'
services:
  promtool:
    image: prom/prometheus
    ports:
      - 9090:9090
    volumes:
      - type: bind
        source: ./prometheus.yml
        target: /etc/prometheus/prometheus.yml
  grafana:
    image: grafana/grafana
    ports:
      - 3000:3000
  alertmanager:
    image: prom/alertmanager
    ports:
      - 9093:9093
    volumes:
      - type: bind
        source: ./alertmgr.yml
        target: /etc/alertmanager/config.yml