version: '3.3'
services:
  promtool:
    image: prom/prometheus:v2.17.2
    ports:
      - 9090:9090
    volumes:
      - type: bind
        source: ./prometheus.yml
        target: /etc/prometheus/prometheus.yml
      - type: bind
        source: ./sample.rule
        target: /etc/prometheus/sample.rule
  grafana:
    image: grafana/grafana:6.7.3
    ports:
      - 3000:3000
  alertmanager:
    image: prom/alertmanager:v0.20.0
    ports:
      - 9093:9093
    volumes:
      - type: bind
        source: ./alertmgr.yml
        target: /etc/alertmanager/alertmanager.yml
