spring:
  #H2 Configuration
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    url: jdbc:h2:file:~/test
    username: sa
    password:
    driver-class-name: org.h2.Driver

#Convenience only,
#should be normally secured.
endpoints:
  sensitive: false